// build.gradle.kts — ifrku-website
//
// Provides Gradle lifecycle tasks that delegate to Jekyll/Bundler.
// Java/Kotlin source is minimal; the primary artefact is a static site
// generated by Jekyll from Markdown source files.

tasks.register<Exec>("bundleInstall") {
    description = "Install Ruby gem dependencies via Bundler."
    group = "jekyll"
    commandLine("bundle", "install")
}

tasks.register<Exec>("jekyllBuild") {
    description = "Build the Jekyll site into _site/."
    group = "jekyll"
    dependsOn("bundleInstall")
    commandLine("bundle", "exec", "jekyll", "build")
}

tasks.register<Exec>("jekyllServe") {
    description = "Serve the Jekyll site locally with live-reload."
    group = "jekyll"
    dependsOn("bundleInstall")
    commandLine("bundle", "exec", "jekyll", "serve", "--livereload")
}

tasks.register<Delete>("cleanSite") {
    description = "Delete the generated _site/ directory."
    group = "jekyll"
    delete("_site")
}

// Wire into the standard Gradle lifecycle.
tasks.named("assemble") { dependsOn("jekyllBuild") }
tasks.named("clean")    { dependsOn("cleanSite") }
